#!/usr/bin/env python3
"""
Maintenance tool for the llm-knowledge-base.

This script runs maintenance tasks on the knowledge base vault,
with a focus on drift detection.

Usage:
    python tools/maintenence/maintenence.py
    python tools/maintenence/maintenence.py --vault /path/to/knowledge-base
"""

import argparse
from datetime import datetime
from pathlib import Path

# Local import hack so the script works when run directly
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent))
import drift


def run_drift_detection(vault_path: Path) -> dict:
    """Run drift detection and return the results."""
    print("  [DRIFT] Checking for changes in wiki/...")
    results = drift.check_drift(vault_path)

    if results["clean"]:
        print("  [DRIFT] No changes detected.")
    else:
        print(f"  [DRIFT] Changes found — "
              f"Added: {len(results['added'])}, "
              f"Removed: {len(results['removed'])}, "
              f"Changed: {len(results['changed'])}")

    return results


def scan_unprocessed_clippings(vault_path: Path) -> dict:
    """Scan the root Clippings/ folder as L4 unprocessed material."""
    clippings_path = vault_path / "Clippings"

    if not clippings_path.exists():
        return {"count": 0, "recent": []}

    files = list(clippings_path.glob("*.md"))
    recent = sorted(files, key=lambda f: f.stat().st_mtime, reverse=True)[:8]

    return {
        "count": len(files),
        "recent": [f.name for f in recent]
    }


def generate_report(vault_path: Path, drift_results: dict, unprocessed: dict) -> Path:
    """Generate and write a maintenance report to raw/sessions/."""
    today = datetime.now().strftime("%Y-%m-%d")
    report_name = f"maintenence-{today}.md"
    report_path = vault_path / "raw" / "sessions" / report_name

    print(f"  [REPORT] Writing report -> {report_path}")

    lines = [
        f"# Maintenance Report — {today}",
        "",
        "## Drift Detection Results",
        "",
        f"- **Total pages tracked**: {drift_results.get('total_tracked', 0)}",
        f"- **Clean**: {drift_results.get('clean', False)}",
        f"- **Added**: {len(drift_results.get('added', []))}",
        f"- **Removed**: {len(drift_results.get('removed', []))}",
        f"- **Changed**: {len(drift_results.get('changed', []))}",
        "",
    ]

    if drift_results.get("added"):
        lines.append("### Added Pages")
        for p in drift_results["added"]:
            lines.append(f"- {p}")
        lines.append("")

    if drift_results.get("removed"):
        lines.append("### Removed Pages")
        for p in drift_results["removed"]:
            lines.append(f"- {p}")
        lines.append("")

    if drift_results.get("changed"):
        lines.append("### Changed Pages")
        for p in drift_results["changed"]:
            lines.append(f"- {p}")
        lines.append("")

    if drift_results.get("clean"):
        lines.append("_No drift detected since last maintenance run._")
        lines.append("")

    # Unprocessed Clippings (L4) section
    lines.append("## Unprocessed Clippings (L4)")
    lines.append("")
    lines.append(f"- **Total files in Clippings/**: {unprocessed.get('count', 0)}")
    lines.append("")

    if unprocessed.get("recent"):
        lines.append("### Most Recent")
        for name in unprocessed["recent"]:
            lines.append(f"- {name}")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("*Generated by tools/maintenence/maintenence.py*")

    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text("\n".join(lines), encoding="utf-8")

    return report_path


def main():
    parser = argparse.ArgumentParser(
        description="Run maintenance tasks on the knowledge base."
    )
    parser.add_argument(
        "--vault",
        type=Path,
        default=Path("."),
        help="Path to the knowledge base root (default: current directory)",
    )
    args = parser.parse_args()

    vault_path = args.vault.resolve()

    print(f"\n=== Maintenance Started ===")
    print(f"Vault: {vault_path}\n")

    drift_results = run_drift_detection(vault_path)
    unprocessed = scan_unprocessed_clippings(vault_path)
    report_path = generate_report(vault_path, drift_results, unprocessed)

    print(f"\nReport written to: {report_path}")
    print("=== Maintenance Finished ===\n")


if __name__ == "__main__":
    main()