import { QuartzComponent, QuartzComponentConstructor, QuartzComponentProps } from "./types"
import style from "./styles/footer.scss"
import { version } from "../../package.json"
import { i18n } from "../i18n"
// @ts-ignore — generated by tools/ledger.mjs at build time
import ledgerData from "./ledgerData.json"

interface Options {
  links: Record<string, string>
}

type LedgerRow = { date: string; label: string; pages: number }

export default ((opts?: Options) => {
  const Footer: QuartzComponent = ({ displayClass, cfg }: QuartzComponentProps) => {
    const year = new Date().getFullYear()
    const links = opts?.links ?? []
    const rows = ledgerData as LedgerRow[]
    const lastPass = rows[0]

    return (
      <footer class={`${displayClass ?? ""}`}>
        <p>
          {i18n(cfg.locale).components.footer.createdWith}{" "}
          <a href="https://quartz.jzhao.xyz/">Quartz v{version}</a> © {year}
        </p>
        {lastPass && (
          <p class="footer-ledger">
            last pass: {lastPass.date} · {lastPass.label} · {lastPass.pages}{" "}
            {lastPass.pages === 1 ? "page" : "pages"}
          </p>
        )}
        <ul>
          {Object.entries(links).map(([text, link]) => (
            <li>
              <a href={link}>{text}</a>
            </li>
          ))}
        </ul>
      </footer>
    )
  }

  Footer.css = style
  return Footer
}) satisfies QuartzComponentConstructor