import { QuartzComponent, QuartzComponentConstructor, QuartzComponentProps } from "./types"
import { SimpleSlug, resolveRelative } from "../util/path"
import { classNames } from "../util/lang"
import Search from "./Search"
import { DOMAINS, colorOf, graphColorRulesFromDomains, spineDomainsForGraph } from "../domains"
// @ts-ignore
import graphScript from "./scripts/graph.inline"
import graphStyle from "./styles/graph.scss"
// @ts-ignore — generated by tools/ledger.mjs at build time
import ledgerData from "./ledgerData.json"

type LedgerRow = { date: string; label: string; pages: number }
const ledgerRows = ledgerData as LedgerRow[]

const SPINE_HUBS = [
  "wiki/Syntheses/First Principles of ICS",
  "wiki/Systems/AI & Agentic Systems/Agentic Engineering",
  "wiki/Self Management/Focus Management - How to Enter & Recover Inside a Work Block",
  "wiki/Minimalism/Minimalism as Systems Design",
  "wiki/Red Team/Red Teaming",
  "wiki/Language/Refold Language Learning System",
]

const spineGraphCfg = {
  drag: true,
  zoom: true,
  depth: -1,
  scale: 1,
  repelForce: 1,
  centerForce: 0.02,
  linkDistance: 55,
  fontSize: 0.55,
  opacityScale: 1,
  showTags: false,
  removeTags: ["system"],
  focusOnHover: true,
  enableRadial: false,
  filterPrefixes: ["wiki/"],
  nodeBaseRadius: 2,
  nodeLinkRadius: 1.18,
  nodeMaxRadius: 9.5,
  nodeRank: "degree" as const,
  nodeLimit: 30,
  mobileNodeLimit: 16,
  colorRules: graphColorRulesFromDomains(),
  spineLayout: true,
  hubSlugs: SPINE_HUBS,
  recentDays: 7,
  spineDomains: spineDomainsForGraph(),
}

const trails = [
  {
    title: "Learning systems",
    sub: "9 notes · the ICS core, start to finish",
    slug: "wiki/Syntheses/First Principles of ICS" as const,
    domainId: "learning",
  },
  {
    title: "Agentic engineering",
    sub: "7 notes · building with agents without losing taste",
    slug: "wiki/Systems/AI & Agentic Systems/Agentic Engineering" as const,
    domainId: "agentic",
  },
  {
    title: "Chinese characters",
    sub: "11 notes · the writing system, decoded in order",
    slug: "wiki/Language/Chinese/How Chinese Characters Work" as const,
    domainId: "language",
  },
  {
    title: "Attention & focus",
    sub: "8 notes · enter, hold, and recover focus",
    slug: "wiki/Self Management/Focus Management - How to Enter & Recover Inside a Work Block" as const,
    domainId: "focus",
  },
]

const AtlasSearch = Search({ placeholder: "Find a note…" })

const HomeLanding: QuartzComponent = (props: QuartzComponentProps) => {
  const { fileData, displayClass } = props
  const here = fileData.slug!

  const domainColor = (id: string) => DOMAINS.find((d) => d.id === id)?.color ?? colorOf(here)

  return (
    <div class={classNames(displayClass, "atlas-home")}>
      <header class="atlas-hero">
        <h1>A second brain for learning systems &amp; agentic engineering</h1>
        <p class="atlas-hero-sub">
          Maintained in the open — partly by LLM agents, under a fixed operating contract.
        </p>
      </header>

      <div class="atlas-search-wrap">
        <AtlasSearch {...props} displayClass="atlas-search" />
      </div>

      <section class="atlas-graph-section">
        <div class="graph atlas-graph home-graph-embed">
          <div class="graph-outer">
            <div class="graph-container" data-cfg={JSON.stringify(spineGraphCfg)}></div>
          </div>
        </div>
        <div class="atlas-legend">
          {DOMAINS.map((d) => (
            <button
              type="button"
              class="atlas-legend-chip"
              data-domain-id={d.id}
              style={`border-color: ${d.color}; color: ${d.color}`}
            >
              {d.label}
            </button>
          ))}
          <span class="atlas-legend-hint">click a domain to filter · ring = updated this week</span>
        </div>
      </section>

      {ledgerRows.length > 0 && (
        <div class="atlas-ledger">
          {ledgerRows.map((row, i) => (
            <p class={i === 0 ? "atlas-ledger-line atlas-ledger-last" : "atlas-ledger-line atlas-ledger-prev"}>
              <span class="atlas-ledger-label">{i === 0 ? "last pass" : "previous"}</span>
              <span class="atlas-ledger-text">
                {row.date} · {row.label} · {row.pages} {row.pages === 1 ? "page" : "pages"} touched
              </span>
            </p>
          ))}
        </div>
      )}

      <section class="atlas-trails">
        <h2>Trails — guided paths through the wiki</h2>
        <div class="atlas-trail-grid">
          {trails.map((t) => (
            <a
              class="atlas-trail-card"
              href={resolveRelative(here, t.slug as SimpleSlug)}
              style={`border-left-color: ${domainColor(t.domainId)}`}
            >
              <span class="atlas-trail-title">{t.title}</span>
              <span class="atlas-trail-sub">{t.sub}</span>
            </a>
          ))}
        </div>
      </section>
    </div>
  )
}

HomeLanding.css = graphStyle
HomeLanding.afterDOMLoaded = graphScript

export default (() => HomeLanding) satisfies QuartzComponentConstructor